// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANrfvWBuaRUbsU7cMz1UkQcC6Qs-XRjeM',
    appId: '1:826668658239:web:8cca9f5c2cb8ca10d2d28a',
    messagingSenderId: '826668658239',
    projectId: 'trippie-30eeb',
    authDomain: 'trippie-30eeb.firebaseapp.com',
    storageBucket: 'trippie-30eeb.firebasestorage.app',
    measurementId: 'G-HDWPDV1ZGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCm5pqlypQp_ESOFNmUwrxVpzH9S6yA4',
    appId: '1:826668658239:android:cb62132105f5e72ad2d28a',
    messagingSenderId: '826668658239',
    projectId: 'trippie-30eeb',
    storageBucket: 'trippie-30eeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCClhFTXQhme2q6JxIN9XqZmO9SXrablLg',
    appId: '1:826668658239:ios:783ed9574fe5960ed2d28a',
    messagingSenderId: '826668658239',
    projectId: 'trippie-30eeb',
    storageBucket: 'trippie-30eeb.firebasestorage.app',
    iosBundleId: 'com.johannka.trippie',
  );
}
